package enums;

public enum DialogueTypes {
    GREETINGS,
    LIST_TASKS,
    MARK_TASK,
    UNMARK_TASK,
    ADD_TASK,
    DELETE_TASK,
    UNKNOWN_TYPE,
    HELP_MENU,
    COUNT_OF_TASKS,
    GOODBYE,
    INVALID_TASK_NUMBER,
    TASK_NUMBER_OUT_OF_RANGE,
    EMPTY_TASK_NAME,
    DEADLINE_WRONG_FORMAT,
    EVENT_WRONG_FORMAT,
    NO_TASK_IN_LIST,
    ERROR_WHEN_SAVING

}
