package duke.error;

/**
 * The possible errors used in Duke
 */
public enum ErrorTypes {
    INVALID_MARK_COMMAND,
    INVALID_UNMARK_COMMAND,
    INVALID_INPUT,
    INVALID_TODO,
    INVALID_DEADLINE_COMMAND,
    INSUFFICIENT_DEADLINE_ARGUMENT,
    INVALID_EVENT_COMMAND,
    INSUFFICIENT_EVENT_ARGUMENT,
    INVALID_DELETE_COMMAND,
    ERROR_WITH_DIRECTORY,
    INVALID_COMMAND,
    INVALID_FIND_COMMAND,
    INVALID_DATE
}
