package duke.error;

public enum ErrorTypes {
    INVALID_MARK_COMMAND,
    NOT_WITHIN_TASK_COUNT,
    INVALID_UNMARK_COMMAND,
    INVALID_INPUT,
    INVALID_TODO,
    INVALID_DEADLINE_COMMAND,
    INSUFFICIENT_DEADLINE_ARGUMENT,
    INVALID_EVENT_COMMAND,
    INSUFFICIENT_EVENT_ARGUMENT,
    INVALID_DELETE_COMMAND
}
