/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wilsonoh.sagyo;

import static org.junit.Assert.*;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import org.junit.Test;

import wilsonoh.sagyo.tasks.DeadlineTask;
import wilsonoh.sagyo.tasks.EventTask;
import wilsonoh.sagyo.tasks.TodoTask;

public class AppTest {
    @Test
    public void testAddTasks() {
        Main duke = new Main();
        duke.addTask(new TodoTask("foo"));
        duke.addTask(new DeadlineTask("bar", "Friday 4pm"));
        duke.addTask(new EventTask("baz", "monday", "tuesday"));
        String[] expected = new String[] {"1: [T][ ] foo", "2: [D][ ] bar (by: Friday 4pm)",
                                          "3: [E][ ] baz (from: monday to: tuesday)"};
        String[] output = duke.getTasksFormatted();
        assertArrayEquals("Add tasks works", expected, output);
    }

    @Test
    public void testResources() throws IOException {
        InputStream resourceStream = AppTest.class.getClassLoader().getResourceAsStream("test.txt");
        BufferedReader br = new BufferedReader(new InputStreamReader(resourceStream));
        assertEquals(br.readLine(), "testing 123");
    }
}
