/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wilsonoh.sagyo;

import static org.junit.Assert.*;

import org.junit.Test;

public class AppTest {
    @Test
    public void test_addTasks() {
        Main duke = new Main();
        duke.addTask("foo");
        duke.addTask("bar");
        duke.addTask("baz");
        String[] expected = new String[] {"1: [ ] foo", "2: [ ] bar", "3: [ ] baz"};
        String[] output = duke.getTasksFormatted();
        assertArrayEquals("Add tasks works", expected, output);
    }
}
