/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wilsonoh.sagyo;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;

import org.junit.Test;

public class AppTest {
    @Test
    public void testAddTasks() {
        Main duke = new Main();
        duke.addTask("foo");
        duke.addTask("bar");
        duke.addTask("baz");
        String[] expected = new String[] {"1: [ ] foo", "2: [ ] bar", "3: [ ] baz"};
        String[] output = duke.getTasksFormatted();
        assertArrayEquals("Add tasks works", expected, output);
    }

    @Test
    public void testResources() throws IOException {
        InputStream resourceStream = AppTest.class.getClassLoader().getResourceAsStream("test.txt");
        BufferedReader br = new BufferedReader(new InputStreamReader(resourceStream));
        assertEquals(br.readLine(), "testing 123");
    }
}
