remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Rica, a simple text-based chatbot
description: Short for Really-Intelligent-Chat-Assistant, R.I.C.A. is a chatbot written in Java that can provide basic todo list management for you through a text-based UI! Rica is written in Java and follows Object-Oriented Programming paradigms.
