remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Thomas Shelby Bot
description: Thomas Shelby Bot is a task manager chatbot which helps you keep track of todo's, deadlines and events.
show_downloads: true
